#!/usr/bin/env python3
"""Rasterize TrueType fonts into anti-aliased 8-bit glyph atlases.

Emits a C header with one slop_font per face. Each glyph stores its bitmap
offset from the pen origin (baseline at x=pen, y=baseline) plus its position
inside the packed atlas, so the C renderer is a tight blit loop.
"""
import sys, os
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
NGLYPHS = LAST - FIRST + 1
ATLAS_W = 512

FACES = [
    ("slop_font_small",  "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14),
    ("slop_font_body",   "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 17),
    ("slop_font_bold",   "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 17),
    ("slop_font_title",  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 22),
    ("slop_font_mono",   "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 16),
    ("slop_font_monob",  "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", 16),
]


def build_face(sym, path, size):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    pad = 4

    glyphs, crops = [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(font.getlength(ch)))
        img = Image.new("L", (size * 2 + 8, size * 2 + 8), 0)
        ImageDraw.Draw(img).text((pad, pad + ascent), ch, font=font, fill=255,
                                 anchor="ls")
        bbox = img.getbbox()
        if bbox is None:
            glyphs.append((0, 0, 0, 0, adv))
            crops.append(None)
            continue
        x0, y0, x1, y1 = bbox
        crops.append(img.crop(bbox))
        glyphs.append((x0 - pad, y0 - (pad + ascent), x1 - x0, y1 - y0, adv))

    x = y = row_h = 0
    placements = []
    for crop in crops:
        if crop is None:
            placements.append(None)
            continue
        w, h = crop.size
        if x + w > ATLAS_W:
            x, y, row_h = 0, y + row_h, 0
        placements.append((x, y))
        x += w
        row_h = max(row_h, h)
    atlas_h = y + row_h
    atlas = Image.new("L", (ATLAS_W, atlas_h), 0)
    for crop, pos in zip(crops, placements):
        if crop is not None:
            atlas.paste(crop, pos)
    data = atlas.tobytes()

    out = [f"/* {sym}: {os.path.basename(path)} {size}px, atlas {ATLAS_W}x{atlas_h} */",
           f"static const unsigned char {sym}_atlas[] = {{"]
    for i in range(0, len(data), 32):
        out.append(",".join(str(b) for b in data[i:i + 32]) + ",")
    out.append("};")
    out.append(f"static const slop_glyph {sym}_glyphs[{NGLYPHS}] = {{")
    for (bx, by, w, h, adv), pos in zip(glyphs, placements):
        ax, ay = pos if pos else (0, 0)
        out.append(f"{{{bx},{by},{w},{h},{adv},{ax},{ay}}},")
    out.append("};")
    out.append(f"const slop_font {sym} = "
               f"{{{height},{ascent},{ATLAS_W},{atlas_h},{sym}_atlas,{sym}_glyphs}};")
    return "\n".join(out), len(data)


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "libslop/font_data.h"
    parts = ["/* Auto-generated by tools/mkfont.py -- do not edit. */",
             "#ifndef SLOP_FONT_DATA_H", "#define SLOP_FONT_DATA_H",
             '#include "slop.h"', ""]
    total = 0
    for sym, path, size in FACES:
        if not os.path.exists(path):
            print(f"!! missing {path}", file=sys.stderr)
            continue
        code, n = build_face(sym, path, size)
        parts.append(code)
        total += n
        print(f"{sym}: {n} bytes")
    parts.append("#endif")
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(parts) + "\n")
    print(f"total {total} bytes -> {out_path}")


if __name__ == "__main__":
    main()
